import{a as v,S as L,i as u}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))m(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&m(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function m(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function y(a,t){try{return(await v.get("https://pixabay.com/api/",{params:{key:"42630881-770530465aa98d154d18ed059",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch{return console.error(`Error: ${response.status}`),[]}}const b=document.querySelector(".gallery");let S=new L(".gallery-link",{captionsData:"alt",captionDelay:250});function f(a){if(a.hits.length===0)return u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});const t=a.hits.map(s=>`<li class="gallery-item">
                <a class="gallery-link" href="${s.largeImageURL}">
                    <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}">
                </a>
            <div class="gallery-info">
                <p class="card">Likes <span class="card-value">${s.likes}</span></p>
                <p class="card">Views <span class="card-value">${s.views}</span></p>
                <p class="card">Comments <span class="card-value">${s.comments}</span></p>
                <p class="card">Downloads <span class="card-value">${s.downloads}</span></p>
            </div>
        </li>`).join("");b.insertAdjacentHTML("beforeend",t),S.refresh()}const c=document.querySelector(".form"),w=document.querySelector(".form-input"),g=document.querySelector(".gallery"),i=document.querySelector(".loader"),d=document.querySelector(".btn-load");let o,p,n;c.addEventListener("submit",q);async function q(a){if(a.preventDefault(),o=1,n=w.value.trim(),n==="")return c.reset(),u.error({message:"Enter search image name",position:"topRight"});i.classList.remove("visually-hidden");try{const t=await y(n,o);p=Math.ceil(t.total/15),g.innerHTML="",f(t)}catch(t){console.log(t)}i.classList.add("visually-hidden"),h(),c.reset()}d.addEventListener("click",$);async function $(){o+=1,i.classList.remove("visually-hidden"),o===p&&u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});const a=await y(n,o);f(a),i.classList.add("visually-hidden"),h();const t=g.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:t*2})}function h(){o>=p?d.classList.add("visually-hidden"):d.classList.remove("visually-hidden")}
//# sourceMappingURL=commonHelpers.js.map
